discovery:
  engine: zookeeper
  zookeeper:
    nodes:
      - 127.0.0.1:2181
server:
  grpc:
    addr: 0.0.0.0:9002
    timeout: "10s"
database:
  mongodb:
    address: mongodb://127.0.0.1:27017
    username: rockim
    password: rockim2022
    database: rockim
    authSource: admin