discovery:
  engine: etcd
  etcd:
    nodes:
      - 127.0.0.1:2379
server:
  grpc:
    addr: :6101
    timeout: "10s"
database:
  mongodb:
    address: mongodb://127.0.0.1:27017
    username: rockim
    password: rockim2022
    database: rockim
    authSource: admin
  redis:
    prefix: "ROCKIM:"
    addr:
      - 127.0.0.1:6379
    password: ""