// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package admin

import (
	"github.com/go-kratos/kratos/v2"
	"rockim/app/access/admin/biz"
	"rockim/app/access/admin/conf"
	"rockim/app/access/admin/data"
	"rockim/app/access/admin/data/grpc"
	"rockim/app/access/admin/server"
	"rockim/app/access/admin/service/manager"
	"rockim/app/access/admin/service/tenant"
	"rockim/pkg/component/discovery"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(env *conf.Env, config *discovery.Config, confServer *conf.Server) (*kratos.App, error) {
	registryDiscovery, err := discovery.NewDiscovery(config)
	if err != nil {
		return nil, err
	}
	userAPIClient, err := grpc.NewUserClient(registryDiscovery)
	if err != nil {
		return nil, err
	}
	userRepo := data.NewUserRepo(userAPIClient)
	authUseCase := biz.NewAuthUseCase(userRepo)
	authService := manager.NewAuthService(authUseCase)
	managerServiceGroup := server.NewManagerServiceGroup(authService)
	tenantAuthService := tenant.NewAuthService(authUseCase)
	tenantServiceGroup := server.NewTenantServiceGroup(tenantAuthService)
	httpServer := server.NewHTTPServer(confServer, managerServiceGroup, tenantServiceGroup)
	app := newApp(env, httpServer)
	return app, nil
}
