// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.0
// source: api/rockim/admin/tenant/v1/types/tenant.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	v1 "rockim/api/rockim/shared/enums/v1"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TenantUser 商户用户
type TenantUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 商户用户ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 创建时间
	CreateTime int64 `protobuf:"varint,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// 登录名
	Account string `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	// 用户名称
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *TenantUser) Reset() {
	*x = TenantUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_admin_tenant_v1_types_tenant_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TenantUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUser) ProtoMessage() {}

func (x *TenantUser) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_admin_tenant_v1_types_tenant_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUser.ProtoReflect.Descriptor instead.
func (*TenantUser) Descriptor() ([]byte, []int) {
	return file_api_rockim_admin_tenant_v1_types_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *TenantUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TenantUser) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *TenantUser) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *TenantUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// TenantRole 商户角色
type TenantRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 角色ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 创建时间
	CreateTime int64 `protobuf:"varint,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// 角色名称
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *TenantRole) Reset() {
	*x = TenantRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_admin_tenant_v1_types_tenant_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TenantRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantRole) ProtoMessage() {}

func (x *TenantRole) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_admin_tenant_v1_types_tenant_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantRole.ProtoReflect.Descriptor instead.
func (*TenantRole) Descriptor() ([]byte, []int) {
	return file_api_rockim_admin_tenant_v1_types_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *TenantRole) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TenantRole) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *TenantRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// TenantResource 商户资源
type TenantResource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 资源ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 创建时间
	CreateTime int64 `protobuf:"varint,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// 分类
	Category v1.TenantResourceCategory `protobuf:"varint,4,opt,name=category,proto3,enum=rockim.shared.enums.v1.TenantResourceCategory" json:"category,omitempty"`
	// 资源名称
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// 上级ID
	ParentId string `protobuf:"bytes,6,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// URL
	Url string `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	// ICON
	Icon string `protobuf:"bytes,8,opt,name=icon,proto3" json:"icon,omitempty"`
	// 排序号
	Order int32 `protobuf:"varint,9,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *TenantResource) Reset() {
	*x = TenantResource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_admin_tenant_v1_types_tenant_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TenantResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantResource) ProtoMessage() {}

func (x *TenantResource) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_admin_tenant_v1_types_tenant_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantResource.ProtoReflect.Descriptor instead.
func (*TenantResource) Descriptor() ([]byte, []int) {
	return file_api_rockim_admin_tenant_v1_types_tenant_proto_rawDescGZIP(), []int{2}
}

func (x *TenantResource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TenantResource) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *TenantResource) GetCategory() v1.TenantResourceCategory {
	if x != nil {
		return x.Category
	}
	return v1.TenantResourceCategory_TENANT_RESOURCE_CATEGORY_INVALID
}

func (x *TenantResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TenantResource) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *TenantResource) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *TenantResource) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *TenantResource) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type TenantResourceTree struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource *TenantResource       `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Children []*TenantResourceTree `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
}

func (x *TenantResourceTree) Reset() {
	*x = TenantResourceTree{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_admin_tenant_v1_types_tenant_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TenantResourceTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantResourceTree) ProtoMessage() {}

func (x *TenantResourceTree) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_admin_tenant_v1_types_tenant_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantResourceTree.ProtoReflect.Descriptor instead.
func (*TenantResourceTree) Descriptor() ([]byte, []int) {
	return file_api_rockim_admin_tenant_v1_types_tenant_proto_rawDescGZIP(), []int{3}
}

func (x *TenantResourceTree) GetResource() *TenantResource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *TenantResourceTree) GetChildren() []*TenantResourceTree {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_api_rockim_admin_tenant_v1_types_tenant_proto protoreflect.FileDescriptor

var file_api_rockim_admin_tenant_v1_types_tenant_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2f, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2f, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2f, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x1c, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x74, 0x65,
	0x6e, 0x61, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x1a, 0x23, 0x72,
	0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x65, 0x6e, 0x75,
	0x6d, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x6b, 0x0a, 0x0a, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x51, 0x0a, 0x0a, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0xfa, 0x01, 0x0a, 0x0e, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f,
	0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x4a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2e, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69,
	0x6d, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22,
	0xac, 0x01, 0x0a, 0x12, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x54, 0x72, 0x65, 0x65, 0x12, 0x48, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69,
	0x6d, 0x2e, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x2e, 0x76,
	0x31, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x12, 0x4c, 0x0a, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x30, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x2e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x54, 0x65, 0x6e, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x54, 0x72, 0x65, 0x65, 0x52, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x42, 0x2f,
	0x5a, 0x2d, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x6f, 0x63,
	0x6b, 0x69, 0x6d, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x74,
	0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x3b, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_rockim_admin_tenant_v1_types_tenant_proto_rawDescOnce sync.Once
	file_api_rockim_admin_tenant_v1_types_tenant_proto_rawDescData = file_api_rockim_admin_tenant_v1_types_tenant_proto_rawDesc
)

func file_api_rockim_admin_tenant_v1_types_tenant_proto_rawDescGZIP() []byte {
	file_api_rockim_admin_tenant_v1_types_tenant_proto_rawDescOnce.Do(func() {
		file_api_rockim_admin_tenant_v1_types_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_rockim_admin_tenant_v1_types_tenant_proto_rawDescData)
	})
	return file_api_rockim_admin_tenant_v1_types_tenant_proto_rawDescData
}

var file_api_rockim_admin_tenant_v1_types_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_rockim_admin_tenant_v1_types_tenant_proto_goTypes = []interface{}{
	(*TenantUser)(nil),             // 0: rockim.admin.tenant.v1.types.TenantUser
	(*TenantRole)(nil),             // 1: rockim.admin.tenant.v1.types.TenantRole
	(*TenantResource)(nil),         // 2: rockim.admin.tenant.v1.types.TenantResource
	(*TenantResourceTree)(nil),     // 3: rockim.admin.tenant.v1.types.TenantResourceTree
	(v1.TenantResourceCategory)(0), // 4: rockim.shared.enums.v1.TenantResourceCategory
}
var file_api_rockim_admin_tenant_v1_types_tenant_proto_depIdxs = []int32{
	4, // 0: rockim.admin.tenant.v1.types.TenantResource.category:type_name -> rockim.shared.enums.v1.TenantResourceCategory
	2, // 1: rockim.admin.tenant.v1.types.TenantResourceTree.resource:type_name -> rockim.admin.tenant.v1.types.TenantResource
	3, // 2: rockim.admin.tenant.v1.types.TenantResourceTree.children:type_name -> rockim.admin.tenant.v1.types.TenantResourceTree
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_rockim_admin_tenant_v1_types_tenant_proto_init() }
func file_api_rockim_admin_tenant_v1_types_tenant_proto_init() {
	if File_api_rockim_admin_tenant_v1_types_tenant_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_rockim_admin_tenant_v1_types_tenant_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TenantUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rockim_admin_tenant_v1_types_tenant_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TenantRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rockim_admin_tenant_v1_types_tenant_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TenantResource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rockim_admin_tenant_v1_types_tenant_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TenantResourceTree); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_rockim_admin_tenant_v1_types_tenant_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_rockim_admin_tenant_v1_types_tenant_proto_goTypes,
		DependencyIndexes: file_api_rockim_admin_tenant_v1_types_tenant_proto_depIdxs,
		MessageInfos:      file_api_rockim_admin_tenant_v1_types_tenant_proto_msgTypes,
	}.Build()
	File_api_rockim_admin_tenant_v1_types_tenant_proto = out.File
	file_api_rockim_admin_tenant_v1_types_tenant_proto_rawDesc = nil
	file_api_rockim_admin_tenant_v1_types_tenant_proto_goTypes = nil
	file_api_rockim_admin_tenant_v1_types_tenant_proto_depIdxs = nil
}
