// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/go-kratos/kratos/v2"
	"rockim/app/logic/user/biz"
	"rockim/app/logic/user/conf"
	"rockim/app/logic/user/data"
	"rockim/app/logic/user/server"
	"rockim/app/logic/user/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(env *conf.Env, confServer *conf.Server) (*kratos.App, error) {
	dataData, err := data.NewData()
	if err != nil {
		return nil, err
	}
	greeterRepo := data.NewUserRepo(dataData)
	greeterUsecase := biz.NewUserUseCase(greeterRepo)
	greeterService := service.NewUserService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService)
	app := newApp(env, grpcServer)
	return app, nil
}
