// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.0
// source: rockim/service/comet/v1/comet.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChannelAPIClient is the client API for ChannelAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChannelAPIClient interface {
	// Push 推送数据
	Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error)
	// PushGroup 推送数据到一个组
	PushGroup(ctx context.Context, in *PushGroupRequest, opts ...grpc.CallOption) (*PushGroupResponse, error)
}

type channelAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewChannelAPIClient(cc grpc.ClientConnInterface) ChannelAPIClient {
	return &channelAPIClient{cc}
}

func (c *channelAPIClient) Push(ctx context.Context, in *PushRequest, opts ...grpc.CallOption) (*PushResponse, error) {
	out := new(PushResponse)
	err := c.cc.Invoke(ctx, "/rockim.service.comet.v1.ChannelAPI/Push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *channelAPIClient) PushGroup(ctx context.Context, in *PushGroupRequest, opts ...grpc.CallOption) (*PushGroupResponse, error) {
	out := new(PushGroupResponse)
	err := c.cc.Invoke(ctx, "/rockim.service.comet.v1.ChannelAPI/PushGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChannelAPIServer is the server API for ChannelAPI service.
// All implementations must embed UnimplementedChannelAPIServer
// for forward compatibility
type ChannelAPIServer interface {
	// Push 推送数据
	Push(context.Context, *PushRequest) (*PushResponse, error)
	// PushGroup 推送数据到一个组
	PushGroup(context.Context, *PushGroupRequest) (*PushGroupResponse, error)
	mustEmbedUnimplementedChannelAPIServer()
}

// UnimplementedChannelAPIServer must be embedded to have forward compatible implementations.
type UnimplementedChannelAPIServer struct {
}

func (UnimplementedChannelAPIServer) Push(context.Context, *PushRequest) (*PushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedChannelAPIServer) PushGroup(context.Context, *PushGroupRequest) (*PushGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushGroup not implemented")
}
func (UnimplementedChannelAPIServer) mustEmbedUnimplementedChannelAPIServer() {}

// UnsafeChannelAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChannelAPIServer will
// result in compilation errors.
type UnsafeChannelAPIServer interface {
	mustEmbedUnimplementedChannelAPIServer()
}

func RegisterChannelAPIServer(s grpc.ServiceRegistrar, srv ChannelAPIServer) {
	s.RegisterService(&ChannelAPI_ServiceDesc, srv)
}

func _ChannelAPI_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelAPIServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rockim.service.comet.v1.ChannelAPI/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelAPIServer).Push(ctx, req.(*PushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChannelAPI_PushGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChannelAPIServer).PushGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rockim.service.comet.v1.ChannelAPI/PushGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChannelAPIServer).PushGroup(ctx, req.(*PushGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChannelAPI_ServiceDesc is the grpc.ServiceDesc for ChannelAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChannelAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rockim.service.comet.v1.ChannelAPI",
	HandlerType: (*ChannelAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Push",
			Handler:    _ChannelAPI_Push_Handler,
		},
		{
			MethodName: "PushGroup",
			Handler:    _ChannelAPI_PushGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rockim/service/comet/v1/comet.proto",
}
