// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.0
// source: api/rockim/service/platform/v1/plat_resource.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PlatResourceAPIClient is the client API for PlatResourceAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlatResourceAPIClient interface {
	// 创建资源
	Create(ctx context.Context, in *PlatResourceCreateRequest, opts ...grpc.CallOption) (*PlatResourceCreateResponse, error)
	// 修改资源
	Update(ctx context.Context, in *PlatResourceUpdateRequest, opts ...grpc.CallOption) (*PlatResourceUpdateResponse, error)
	// 删除资源
	Delete(ctx context.Context, in *PlatResourceDeleteRequest, opts ...grpc.CallOption) (*PlatResourceDeleteResponse, error)
	// 获取平台资源列表
	List(ctx context.Context, in *PlatResourceListRequest, opts ...grpc.CallOption) (*PlatResourceListResponse, error)
	// 获取平台资源列表 (指定id列表)
	ListByIds(ctx context.Context, in *PlatResourceListByIdsRequest, opts ...grpc.CallOption) (*PlatResourceListByIdsResponse, error)
}

type platResourceAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewPlatResourceAPIClient(cc grpc.ClientConnInterface) PlatResourceAPIClient {
	return &platResourceAPIClient{cc}
}

func (c *platResourceAPIClient) Create(ctx context.Context, in *PlatResourceCreateRequest, opts ...grpc.CallOption) (*PlatResourceCreateResponse, error) {
	out := new(PlatResourceCreateResponse)
	err := c.cc.Invoke(ctx, "/rockim.service.platform.v1.PlatResourceAPI/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platResourceAPIClient) Update(ctx context.Context, in *PlatResourceUpdateRequest, opts ...grpc.CallOption) (*PlatResourceUpdateResponse, error) {
	out := new(PlatResourceUpdateResponse)
	err := c.cc.Invoke(ctx, "/rockim.service.platform.v1.PlatResourceAPI/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platResourceAPIClient) Delete(ctx context.Context, in *PlatResourceDeleteRequest, opts ...grpc.CallOption) (*PlatResourceDeleteResponse, error) {
	out := new(PlatResourceDeleteResponse)
	err := c.cc.Invoke(ctx, "/rockim.service.platform.v1.PlatResourceAPI/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platResourceAPIClient) List(ctx context.Context, in *PlatResourceListRequest, opts ...grpc.CallOption) (*PlatResourceListResponse, error) {
	out := new(PlatResourceListResponse)
	err := c.cc.Invoke(ctx, "/rockim.service.platform.v1.PlatResourceAPI/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platResourceAPIClient) ListByIds(ctx context.Context, in *PlatResourceListByIdsRequest, opts ...grpc.CallOption) (*PlatResourceListByIdsResponse, error) {
	out := new(PlatResourceListByIdsResponse)
	err := c.cc.Invoke(ctx, "/rockim.service.platform.v1.PlatResourceAPI/ListByIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlatResourceAPIServer is the server API for PlatResourceAPI service.
// All implementations must embed UnimplementedPlatResourceAPIServer
// for forward compatibility
type PlatResourceAPIServer interface {
	// 创建资源
	Create(context.Context, *PlatResourceCreateRequest) (*PlatResourceCreateResponse, error)
	// 修改资源
	Update(context.Context, *PlatResourceUpdateRequest) (*PlatResourceUpdateResponse, error)
	// 删除资源
	Delete(context.Context, *PlatResourceDeleteRequest) (*PlatResourceDeleteResponse, error)
	// 获取平台资源列表
	List(context.Context, *PlatResourceListRequest) (*PlatResourceListResponse, error)
	// 获取平台资源列表 (指定id列表)
	ListByIds(context.Context, *PlatResourceListByIdsRequest) (*PlatResourceListByIdsResponse, error)
	mustEmbedUnimplementedPlatResourceAPIServer()
}

// UnimplementedPlatResourceAPIServer must be embedded to have forward compatible implementations.
type UnimplementedPlatResourceAPIServer struct {
}

func (UnimplementedPlatResourceAPIServer) Create(context.Context, *PlatResourceCreateRequest) (*PlatResourceCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedPlatResourceAPIServer) Update(context.Context, *PlatResourceUpdateRequest) (*PlatResourceUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedPlatResourceAPIServer) Delete(context.Context, *PlatResourceDeleteRequest) (*PlatResourceDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedPlatResourceAPIServer) List(context.Context, *PlatResourceListRequest) (*PlatResourceListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedPlatResourceAPIServer) ListByIds(context.Context, *PlatResourceListByIdsRequest) (*PlatResourceListByIdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListByIds not implemented")
}
func (UnimplementedPlatResourceAPIServer) mustEmbedUnimplementedPlatResourceAPIServer() {}

// UnsafePlatResourceAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlatResourceAPIServer will
// result in compilation errors.
type UnsafePlatResourceAPIServer interface {
	mustEmbedUnimplementedPlatResourceAPIServer()
}

func RegisterPlatResourceAPIServer(s grpc.ServiceRegistrar, srv PlatResourceAPIServer) {
	s.RegisterService(&PlatResourceAPI_ServiceDesc, srv)
}

func _PlatResourceAPI_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatResourceCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatResourceAPIServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rockim.service.platform.v1.PlatResourceAPI/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatResourceAPIServer).Create(ctx, req.(*PlatResourceCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatResourceAPI_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatResourceUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatResourceAPIServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rockim.service.platform.v1.PlatResourceAPI/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatResourceAPIServer).Update(ctx, req.(*PlatResourceUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatResourceAPI_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatResourceDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatResourceAPIServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rockim.service.platform.v1.PlatResourceAPI/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatResourceAPIServer).Delete(ctx, req.(*PlatResourceDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatResourceAPI_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatResourceListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatResourceAPIServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rockim.service.platform.v1.PlatResourceAPI/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatResourceAPIServer).List(ctx, req.(*PlatResourceListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatResourceAPI_ListByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlatResourceListByIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatResourceAPIServer).ListByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rockim.service.platform.v1.PlatResourceAPI/ListByIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatResourceAPIServer).ListByIds(ctx, req.(*PlatResourceListByIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlatResourceAPI_ServiceDesc is the grpc.ServiceDesc for PlatResourceAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlatResourceAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rockim.service.platform.v1.PlatResourceAPI",
	HandlerType: (*PlatResourceAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _PlatResourceAPI_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _PlatResourceAPI_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _PlatResourceAPI_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _PlatResourceAPI_List_Handler,
		},
		{
			MethodName: "ListByIds",
			Handler:    _PlatResourceAPI_ListByIds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/rockim/service/platform/v1/plat_resource.proto",
}
