// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.0
// source: api/rockim/service/platform/v1/plat_resource.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	types "rockim/api/rockim/service/platform/v1/types"
	v1 "rockim/api/rockim/shared/enums/v1"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlatResourceOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category v1.PlatResourceCategory `protobuf:"varint,1,opt,name=category,proto3,enum=rockim.shared.enums.v1.PlatResourceCategory" json:"category,omitempty"`
	// 菜单名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 上级ID
	ParentId string `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	// URL
	Url string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	// ICON
	Icon string `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	// 排序号
	Order int32 `protobuf:"varint,6,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *PlatResourceOptions) Reset() {
	*x = PlatResourceOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatResourceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatResourceOptions) ProtoMessage() {}

func (x *PlatResourceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatResourceOptions.ProtoReflect.Descriptor instead.
func (*PlatResourceOptions) Descriptor() ([]byte, []int) {
	return file_api_rockim_service_platform_v1_plat_resource_proto_rawDescGZIP(), []int{0}
}

func (x *PlatResourceOptions) GetCategory() v1.PlatResourceCategory {
	if x != nil {
		return x.Category
	}
	return v1.PlatResourceCategory_PLAT_RESOURCE_CATEGORY_INVALID
}

func (x *PlatResourceOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlatResourceOptions) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *PlatResourceOptions) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PlatResourceOptions) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *PlatResourceOptions) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type PlatResourceCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options *PlatResourceOptions `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *PlatResourceCreateRequest) Reset() {
	*x = PlatResourceCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatResourceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatResourceCreateRequest) ProtoMessage() {}

func (x *PlatResourceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatResourceCreateRequest.ProtoReflect.Descriptor instead.
func (*PlatResourceCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_rockim_service_platform_v1_plat_resource_proto_rawDescGZIP(), []int{1}
}

func (x *PlatResourceCreateRequest) GetOptions() *PlatResourceOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type PlatResourceCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PlatResourceCreateResponse) Reset() {
	*x = PlatResourceCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatResourceCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatResourceCreateResponse) ProtoMessage() {}

func (x *PlatResourceCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatResourceCreateResponse.ProtoReflect.Descriptor instead.
func (*PlatResourceCreateResponse) Descriptor() ([]byte, []int) {
	return file_api_rockim_service_platform_v1_plat_resource_proto_rawDescGZIP(), []int{2}
}

type PlatResourceUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Options *PlatResourceOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *PlatResourceUpdateRequest) Reset() {
	*x = PlatResourceUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatResourceUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatResourceUpdateRequest) ProtoMessage() {}

func (x *PlatResourceUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatResourceUpdateRequest.ProtoReflect.Descriptor instead.
func (*PlatResourceUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_rockim_service_platform_v1_plat_resource_proto_rawDescGZIP(), []int{3}
}

func (x *PlatResourceUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlatResourceUpdateRequest) GetOptions() *PlatResourceOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type PlatResourceUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PlatResourceUpdateResponse) Reset() {
	*x = PlatResourceUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatResourceUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatResourceUpdateResponse) ProtoMessage() {}

func (x *PlatResourceUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatResourceUpdateResponse.ProtoReflect.Descriptor instead.
func (*PlatResourceUpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_rockim_service_platform_v1_plat_resource_proto_rawDescGZIP(), []int{4}
}

type PlatResourceDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PlatResourceDeleteRequest) Reset() {
	*x = PlatResourceDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatResourceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatResourceDeleteRequest) ProtoMessage() {}

func (x *PlatResourceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatResourceDeleteRequest.ProtoReflect.Descriptor instead.
func (*PlatResourceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_rockim_service_platform_v1_plat_resource_proto_rawDescGZIP(), []int{5}
}

func (x *PlatResourceDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PlatResourceDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PlatResourceDeleteResponse) Reset() {
	*x = PlatResourceDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatResourceDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatResourceDeleteResponse) ProtoMessage() {}

func (x *PlatResourceDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatResourceDeleteResponse.ProtoReflect.Descriptor instead.
func (*PlatResourceDeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_rockim_service_platform_v1_plat_resource_proto_rawDescGZIP(), []int{6}
}

type PlatResourceListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PlatResourceListRequest) Reset() {
	*x = PlatResourceListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatResourceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatResourceListRequest) ProtoMessage() {}

func (x *PlatResourceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatResourceListRequest.ProtoReflect.Descriptor instead.
func (*PlatResourceListRequest) Descriptor() ([]byte, []int) {
	return file_api_rockim_service_platform_v1_plat_resource_proto_rawDescGZIP(), []int{7}
}

type PlatResourceListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*types.PlatResource `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *PlatResourceListResponse) Reset() {
	*x = PlatResourceListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatResourceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatResourceListResponse) ProtoMessage() {}

func (x *PlatResourceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatResourceListResponse.ProtoReflect.Descriptor instead.
func (*PlatResourceListResponse) Descriptor() ([]byte, []int) {
	return file_api_rockim_service_platform_v1_plat_resource_proto_rawDescGZIP(), []int{8}
}

func (x *PlatResourceListResponse) GetList() []*types.PlatResource {
	if x != nil {
		return x.List
	}
	return nil
}

type PlatResourceListByIdsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *PlatResourceListByIdsRequest) Reset() {
	*x = PlatResourceListByIdsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatResourceListByIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatResourceListByIdsRequest) ProtoMessage() {}

func (x *PlatResourceListByIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatResourceListByIdsRequest.ProtoReflect.Descriptor instead.
func (*PlatResourceListByIdsRequest) Descriptor() ([]byte, []int) {
	return file_api_rockim_service_platform_v1_plat_resource_proto_rawDescGZIP(), []int{9}
}

func (x *PlatResourceListByIdsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type PlatResourceListByIdsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*types.PlatResource `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *PlatResourceListByIdsResponse) Reset() {
	*x = PlatResourceListByIdsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatResourceListByIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatResourceListByIdsResponse) ProtoMessage() {}

func (x *PlatResourceListByIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatResourceListByIdsResponse.ProtoReflect.Descriptor instead.
func (*PlatResourceListByIdsResponse) Descriptor() ([]byte, []int) {
	return file_api_rockim_service_platform_v1_plat_resource_proto_rawDescGZIP(), []int{10}
}

func (x *PlatResourceListByIdsResponse) GetList() []*types.PlatResource {
	if x != nil {
		return x.List
	}
	return nil
}

var File_api_rockim_service_platform_v1_plat_resource_proto protoreflect.FileDescriptor

var file_api_rockim_service_platform_v1_plat_resource_proto_rawDesc = []byte{
	0x0a, 0x32, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x76, 0x31,
	0x2f, 0x70, 0x6c, 0x61, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31,
	0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2f, 0x72, 0x6f, 0x63, 0x6b, 0x69,
	0x6d, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x25, 0x72, 0x6f, 0x63, 0x6b,
	0x69, 0x6d, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2f,
	0x76, 0x31, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xcc, 0x01, 0x0a, 0x13, 0x50, 0x6c, 0x61, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x48, 0x0a, 0x08, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x72, 0x6f,
	0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x65, 0x6e, 0x75, 0x6d,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x22, 0x70, 0x0a, 0x19, 0x50, 0x6c, 0x61, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x53, 0x0a,
	0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f,
	0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x74,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x42,
	0x08, 0xfa, 0x42, 0x05, 0x8a, 0x01, 0x02, 0x10, 0x01, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x22, 0x1c, 0x0a, 0x1a, 0x50, 0x6c, 0x61, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x80, 0x01, 0x0a, 0x19, 0x50, 0x6c, 0x61, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x53,
	0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2f, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61,
	0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x42, 0x08, 0xfa, 0x42, 0x05, 0x8a, 0x01, 0x02, 0x10, 0x01, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x22, 0x1c, 0x0a, 0x1a, 0x50, 0x6c, 0x61, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x2b, 0x0a, 0x19, 0x50, 0x6c, 0x61, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1c,
	0x0a, 0x1a, 0x50, 0x6c, 0x61, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x19, 0x0a, 0x17,
	0x50, 0x6c, 0x61, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5e, 0x0a, 0x18, 0x50, 0x6c, 0x61, 0x74, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x2e, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x3a, 0x0a, 0x1c, 0x50, 0x6c, 0x61, 0x74, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x92, 0x01, 0x02, 0x08, 0x01, 0x52, 0x03,
	0x69, 0x64, 0x73, 0x22, 0x63, 0x0a, 0x1d, 0x50, 0x6c, 0x61, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x32, 0xf2, 0x04, 0x0a, 0x0f, 0x50, 0x6c, 0x61,
	0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x50, 0x49, 0x12, 0x77, 0x0a, 0x06,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x35, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x36, 0x2e,
	0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x77, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x35, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61,
	0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x36, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x77,
	0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x35, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69,
	0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x36, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61,
	0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x71, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x33, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61,
	0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x34, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x80, 0x01, 0x0a, 0x09, 0x4c,
	0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64, 0x73, 0x12, 0x38, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69,
	0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x49, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x39, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x6c, 0x61, 0x74, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x42, 0x79, 0x49, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2a, 0x5a,
	0x28, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x6f, 0x63, 0x6b,
	0x69, 0x6d, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_rockim_service_platform_v1_plat_resource_proto_rawDescOnce sync.Once
	file_api_rockim_service_platform_v1_plat_resource_proto_rawDescData = file_api_rockim_service_platform_v1_plat_resource_proto_rawDesc
)

func file_api_rockim_service_platform_v1_plat_resource_proto_rawDescGZIP() []byte {
	file_api_rockim_service_platform_v1_plat_resource_proto_rawDescOnce.Do(func() {
		file_api_rockim_service_platform_v1_plat_resource_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_rockim_service_platform_v1_plat_resource_proto_rawDescData)
	})
	return file_api_rockim_service_platform_v1_plat_resource_proto_rawDescData
}

var file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_rockim_service_platform_v1_plat_resource_proto_goTypes = []interface{}{
	(*PlatResourceOptions)(nil),           // 0: rockim.service.platform.v1.PlatResourceOptions
	(*PlatResourceCreateRequest)(nil),     // 1: rockim.service.platform.v1.PlatResourceCreateRequest
	(*PlatResourceCreateResponse)(nil),    // 2: rockim.service.platform.v1.PlatResourceCreateResponse
	(*PlatResourceUpdateRequest)(nil),     // 3: rockim.service.platform.v1.PlatResourceUpdateRequest
	(*PlatResourceUpdateResponse)(nil),    // 4: rockim.service.platform.v1.PlatResourceUpdateResponse
	(*PlatResourceDeleteRequest)(nil),     // 5: rockim.service.platform.v1.PlatResourceDeleteRequest
	(*PlatResourceDeleteResponse)(nil),    // 6: rockim.service.platform.v1.PlatResourceDeleteResponse
	(*PlatResourceListRequest)(nil),       // 7: rockim.service.platform.v1.PlatResourceListRequest
	(*PlatResourceListResponse)(nil),      // 8: rockim.service.platform.v1.PlatResourceListResponse
	(*PlatResourceListByIdsRequest)(nil),  // 9: rockim.service.platform.v1.PlatResourceListByIdsRequest
	(*PlatResourceListByIdsResponse)(nil), // 10: rockim.service.platform.v1.PlatResourceListByIdsResponse
	(v1.PlatResourceCategory)(0),          // 11: rockim.shared.enums.v1.PlatResourceCategory
	(*types.PlatResource)(nil),            // 12: rockim.service.platform.v1.types.PlatResource
}
var file_api_rockim_service_platform_v1_plat_resource_proto_depIdxs = []int32{
	11, // 0: rockim.service.platform.v1.PlatResourceOptions.category:type_name -> rockim.shared.enums.v1.PlatResourceCategory
	0,  // 1: rockim.service.platform.v1.PlatResourceCreateRequest.options:type_name -> rockim.service.platform.v1.PlatResourceOptions
	0,  // 2: rockim.service.platform.v1.PlatResourceUpdateRequest.options:type_name -> rockim.service.platform.v1.PlatResourceOptions
	12, // 3: rockim.service.platform.v1.PlatResourceListResponse.list:type_name -> rockim.service.platform.v1.types.PlatResource
	12, // 4: rockim.service.platform.v1.PlatResourceListByIdsResponse.list:type_name -> rockim.service.platform.v1.types.PlatResource
	1,  // 5: rockim.service.platform.v1.PlatResourceAPI.Create:input_type -> rockim.service.platform.v1.PlatResourceCreateRequest
	3,  // 6: rockim.service.platform.v1.PlatResourceAPI.Update:input_type -> rockim.service.platform.v1.PlatResourceUpdateRequest
	5,  // 7: rockim.service.platform.v1.PlatResourceAPI.Delete:input_type -> rockim.service.platform.v1.PlatResourceDeleteRequest
	7,  // 8: rockim.service.platform.v1.PlatResourceAPI.List:input_type -> rockim.service.platform.v1.PlatResourceListRequest
	9,  // 9: rockim.service.platform.v1.PlatResourceAPI.ListByIds:input_type -> rockim.service.platform.v1.PlatResourceListByIdsRequest
	2,  // 10: rockim.service.platform.v1.PlatResourceAPI.Create:output_type -> rockim.service.platform.v1.PlatResourceCreateResponse
	4,  // 11: rockim.service.platform.v1.PlatResourceAPI.Update:output_type -> rockim.service.platform.v1.PlatResourceUpdateResponse
	6,  // 12: rockim.service.platform.v1.PlatResourceAPI.Delete:output_type -> rockim.service.platform.v1.PlatResourceDeleteResponse
	8,  // 13: rockim.service.platform.v1.PlatResourceAPI.List:output_type -> rockim.service.platform.v1.PlatResourceListResponse
	10, // 14: rockim.service.platform.v1.PlatResourceAPI.ListByIds:output_type -> rockim.service.platform.v1.PlatResourceListByIdsResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_rockim_service_platform_v1_plat_resource_proto_init() }
func file_api_rockim_service_platform_v1_plat_resource_proto_init() {
	if File_api_rockim_service_platform_v1_plat_resource_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatResourceOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatResourceCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatResourceCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatResourceUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatResourceUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatResourceDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatResourceDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatResourceListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatResourceListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatResourceListByIdsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatResourceListByIdsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_rockim_service_platform_v1_plat_resource_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_rockim_service_platform_v1_plat_resource_proto_goTypes,
		DependencyIndexes: file_api_rockim_service_platform_v1_plat_resource_proto_depIdxs,
		MessageInfos:      file_api_rockim_service_platform_v1_plat_resource_proto_msgTypes,
	}.Build()
	File_api_rockim_service_platform_v1_plat_resource_proto = out.File
	file_api_rockim_service_platform_v1_plat_resource_proto_rawDesc = nil
	file_api_rockim_service_platform_v1_plat_resource_proto_goTypes = nil
	file_api_rockim_service_platform_v1_plat_resource_proto_depIdxs = nil
}
