// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.0
// source: api/rockim/service/platform/v1/plat_user.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	types1 "rockim/api/rockim/service/platform/v1/types"
	types "rockim/api/rockim/shared/types"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PlatUserOptions 用户选项
type PlatUserOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 账号
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// 名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *PlatUserOptions) Reset() {
	*x = PlatUserOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatUserOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatUserOptions) ProtoMessage() {}

func (x *PlatUserOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatUserOptions.ProtoReflect.Descriptor instead.
func (*PlatUserOptions) Descriptor() ([]byte, []int) {
	return file_api_rockim_service_platform_v1_plat_user_proto_rawDescGZIP(), []int{0}
}

func (x *PlatUserOptions) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *PlatUserOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// PlatUserCreateRequest 用户创建请求
type PlatUserCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options *PlatUserOptions `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	// 密码
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *PlatUserCreateRequest) Reset() {
	*x = PlatUserCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatUserCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatUserCreateRequest) ProtoMessage() {}

func (x *PlatUserCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatUserCreateRequest.ProtoReflect.Descriptor instead.
func (*PlatUserCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_rockim_service_platform_v1_plat_user_proto_rawDescGZIP(), []int{1}
}

func (x *PlatUserCreateRequest) GetOptions() *PlatUserOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *PlatUserCreateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// PlatUserCreateResponse 用户创建响应
type PlatUserCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PlatUserCreateResponse) Reset() {
	*x = PlatUserCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatUserCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatUserCreateResponse) ProtoMessage() {}

func (x *PlatUserCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatUserCreateResponse.ProtoReflect.Descriptor instead.
func (*PlatUserCreateResponse) Descriptor() ([]byte, []int) {
	return file_api_rockim_service_platform_v1_plat_user_proto_rawDescGZIP(), []int{2}
}

// PlatUserUpdateRequest 用户更新请求
type PlatUserUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Options *PlatUserOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
}

func (x *PlatUserUpdateRequest) Reset() {
	*x = PlatUserUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatUserUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatUserUpdateRequest) ProtoMessage() {}

func (x *PlatUserUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatUserUpdateRequest.ProtoReflect.Descriptor instead.
func (*PlatUserUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_rockim_service_platform_v1_plat_user_proto_rawDescGZIP(), []int{3}
}

func (x *PlatUserUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlatUserUpdateRequest) GetOptions() *PlatUserOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// PlatUserUpdateResponse 用户更新响应
type PlatUserUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PlatUserUpdateResponse) Reset() {
	*x = PlatUserUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatUserUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatUserUpdateResponse) ProtoMessage() {}

func (x *PlatUserUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatUserUpdateResponse.ProtoReflect.Descriptor instead.
func (*PlatUserUpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_rockim_service_platform_v1_plat_user_proto_rawDescGZIP(), []int{4}
}

// PlatUserDeleteRequest 用户删除请求
type PlatUserDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PlatUserDeleteRequest) Reset() {
	*x = PlatUserDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatUserDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatUserDeleteRequest) ProtoMessage() {}

func (x *PlatUserDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatUserDeleteRequest.ProtoReflect.Descriptor instead.
func (*PlatUserDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_rockim_service_platform_v1_plat_user_proto_rawDescGZIP(), []int{5}
}

func (x *PlatUserDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// PlatUserDeleteResponse 用户删除响应
type PlatUserDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PlatUserDeleteResponse) Reset() {
	*x = PlatUserDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatUserDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatUserDeleteResponse) ProtoMessage() {}

func (x *PlatUserDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatUserDeleteResponse.ProtoReflect.Descriptor instead.
func (*PlatUserDeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_rockim_service_platform_v1_plat_user_proto_rawDescGZIP(), []int{6}
}

// PlatUserPagingRequest 分页获取用户请求
type PlatUserPagingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paginate *types.Paginating `protobuf:"bytes,1,opt,name=paginate,proto3" json:"paginate,omitempty"`
	Keyword  string            `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
}

func (x *PlatUserPagingRequest) Reset() {
	*x = PlatUserPagingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatUserPagingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatUserPagingRequest) ProtoMessage() {}

func (x *PlatUserPagingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatUserPagingRequest.ProtoReflect.Descriptor instead.
func (*PlatUserPagingRequest) Descriptor() ([]byte, []int) {
	return file_api_rockim_service_platform_v1_plat_user_proto_rawDescGZIP(), []int{7}
}

func (x *PlatUserPagingRequest) GetPaginate() *types.Paginating {
	if x != nil {
		return x.Paginate
	}
	return nil
}

func (x *PlatUserPagingRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

// PlatUserPagingResponse 分页获取用户响应
type PlatUserPagingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 用户列表
	List []*types1.PlatUser `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	// 分页数据
	Paginate *types.Paginated `protobuf:"bytes,2,opt,name=paginate,proto3" json:"paginate,omitempty"`
}

func (x *PlatUserPagingResponse) Reset() {
	*x = PlatUserPagingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatUserPagingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatUserPagingResponse) ProtoMessage() {}

func (x *PlatUserPagingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatUserPagingResponse.ProtoReflect.Descriptor instead.
func (*PlatUserPagingResponse) Descriptor() ([]byte, []int) {
	return file_api_rockim_service_platform_v1_plat_user_proto_rawDescGZIP(), []int{8}
}

func (x *PlatUserPagingResponse) GetList() []*types1.PlatUser {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *PlatUserPagingResponse) GetPaginate() *types.Paginated {
	if x != nil {
		return x.Paginate
	}
	return nil
}

type PlatUserFindRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (x *PlatUserFindRequest) Reset() {
	*x = PlatUserFindRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatUserFindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatUserFindRequest) ProtoMessage() {}

func (x *PlatUserFindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatUserFindRequest.ProtoReflect.Descriptor instead.
func (*PlatUserFindRequest) Descriptor() ([]byte, []int) {
	return file_api_rockim_service_platform_v1_plat_user_proto_rawDescGZIP(), []int{9}
}

func (x *PlatUserFindRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type PlatUserFindResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *types1.PlatUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *PlatUserFindResponse) Reset() {
	*x = PlatUserFindResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatUserFindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatUserFindResponse) ProtoMessage() {}

func (x *PlatUserFindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatUserFindResponse.ProtoReflect.Descriptor instead.
func (*PlatUserFindResponse) Descriptor() ([]byte, []int) {
	return file_api_rockim_service_platform_v1_plat_user_proto_rawDescGZIP(), []int{10}
}

func (x *PlatUserFindResponse) GetUser() *types1.PlatUser {
	if x != nil {
		return x.User
	}
	return nil
}

type PlatUserRoleIdListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserIds []string `protobuf:"bytes,1,rep,name=userIds,proto3" json:"userIds,omitempty"`
}

func (x *PlatUserRoleIdListRequest) Reset() {
	*x = PlatUserRoleIdListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatUserRoleIdListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatUserRoleIdListRequest) ProtoMessage() {}

func (x *PlatUserRoleIdListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatUserRoleIdListRequest.ProtoReflect.Descriptor instead.
func (*PlatUserRoleIdListRequest) Descriptor() ([]byte, []int) {
	return file_api_rockim_service_platform_v1_plat_user_proto_rawDescGZIP(), []int{11}
}

func (x *PlatUserRoleIdListRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type PlatUserRoleIdListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []string `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *PlatUserRoleIdListResponse) Reset() {
	*x = PlatUserRoleIdListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatUserRoleIdListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatUserRoleIdListResponse) ProtoMessage() {}

func (x *PlatUserRoleIdListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatUserRoleIdListResponse.ProtoReflect.Descriptor instead.
func (*PlatUserRoleIdListResponse) Descriptor() ([]byte, []int) {
	return file_api_rockim_service_platform_v1_plat_user_proto_rawDescGZIP(), []int{12}
}

func (x *PlatUserRoleIdListResponse) GetList() []string {
	if x != nil {
		return x.List
	}
	return nil
}

var File_api_rockim_service_platform_v1_plat_user_proto protoreflect.FileDescriptor

var file_api_rockim_service_platform_v1_plat_user_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x76, 0x31,
	0x2f, 0x70, 0x6c, 0x61, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x1a, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x1a, 0x17, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2f, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x76,
	0x31, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x22, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2f, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x70, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x0f, 0x50, 0x6c,
	0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x7a, 0x0a, 0x15, 0x50,
	0x6c, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x45, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x50, 0x6c, 0x61, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x77, 0x0a, 0x15, 0x50, 0x6c, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x45, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x18, 0x0a, 0x16, 0x50, 0x6c,
	0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x30, 0x0a, 0x15, 0x50, 0x6c, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x72, 0x02,
	0x10, 0x01, 0x52, 0x02, 0x69, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x50, 0x6c, 0x61, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x6e, 0x0a, 0x15, 0x50, 0x6c, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x61, 0x67, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x08, 0x70, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x72, 0x6f,
	0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x70, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64,
	0x22, 0x94, 0x01, 0x0a, 0x16, 0x50, 0x6c, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x61, 0x67,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x72, 0x6f, 0x63, 0x6b,
	0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x50, 0x6c, 0x61,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x08, 0x70,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x64, 0x52, 0x08, 0x70,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x22, 0x2f, 0x0a, 0x13, 0x50, 0x6c, 0x61, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x56, 0x0a, 0x14, 0x50, 0x6c, 0x61, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3e, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a,
	0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x22, 0x3f, 0x0a, 0x19, 0x50, 0x6c, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65,
	0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x42, 0x08,
	0xfa, 0x42, 0x05, 0x92, 0x01, 0x02, 0x08, 0x01, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x73, 0x22, 0x30, 0x0a, 0x1a, 0x50, 0x6c, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c,
	0x65, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6c,
	0x69, 0x73, 0x74, 0x32, 0xb9, 0x05, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x41, 0x50, 0x49, 0x12, 0x6f, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x31, 0x2e,
	0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x32, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c,
	0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6f, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x31,
	0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x32, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x6c, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6f, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x31, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x32, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x6c, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6f, 0x0a, 0x06, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x67,
	0x12, 0x31, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c,
	0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x6c, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x69, 0x0a, 0x04, 0x46, 0x69, 0x6e, 0x64, 0x12,
	0x2f, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x30, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c,
	0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x7b, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64,
	0x12, 0x35, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c,
	0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x36, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72,
	0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c,
	0x65, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x2a, 0x5a, 0x28, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x6f,
	0x63, 0x6b, 0x69, 0x6d, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_rockim_service_platform_v1_plat_user_proto_rawDescOnce sync.Once
	file_api_rockim_service_platform_v1_plat_user_proto_rawDescData = file_api_rockim_service_platform_v1_plat_user_proto_rawDesc
)

func file_api_rockim_service_platform_v1_plat_user_proto_rawDescGZIP() []byte {
	file_api_rockim_service_platform_v1_plat_user_proto_rawDescOnce.Do(func() {
		file_api_rockim_service_platform_v1_plat_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_rockim_service_platform_v1_plat_user_proto_rawDescData)
	})
	return file_api_rockim_service_platform_v1_plat_user_proto_rawDescData
}

var file_api_rockim_service_platform_v1_plat_user_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_rockim_service_platform_v1_plat_user_proto_goTypes = []interface{}{
	(*PlatUserOptions)(nil),            // 0: rockim.service.platform.v1.PlatUserOptions
	(*PlatUserCreateRequest)(nil),      // 1: rockim.service.platform.v1.PlatUserCreateRequest
	(*PlatUserCreateResponse)(nil),     // 2: rockim.service.platform.v1.PlatUserCreateResponse
	(*PlatUserUpdateRequest)(nil),      // 3: rockim.service.platform.v1.PlatUserUpdateRequest
	(*PlatUserUpdateResponse)(nil),     // 4: rockim.service.platform.v1.PlatUserUpdateResponse
	(*PlatUserDeleteRequest)(nil),      // 5: rockim.service.platform.v1.PlatUserDeleteRequest
	(*PlatUserDeleteResponse)(nil),     // 6: rockim.service.platform.v1.PlatUserDeleteResponse
	(*PlatUserPagingRequest)(nil),      // 7: rockim.service.platform.v1.PlatUserPagingRequest
	(*PlatUserPagingResponse)(nil),     // 8: rockim.service.platform.v1.PlatUserPagingResponse
	(*PlatUserFindRequest)(nil),        // 9: rockim.service.platform.v1.PlatUserFindRequest
	(*PlatUserFindResponse)(nil),       // 10: rockim.service.platform.v1.PlatUserFindResponse
	(*PlatUserRoleIdListRequest)(nil),  // 11: rockim.service.platform.v1.PlatUserRoleIdListRequest
	(*PlatUserRoleIdListResponse)(nil), // 12: rockim.service.platform.v1.PlatUserRoleIdListResponse
	(*types.Paginating)(nil),           // 13: rockim.shared.types.Paginating
	(*types1.PlatUser)(nil),            // 14: rockim.service.platform.v1.types.PlatUser
	(*types.Paginated)(nil),            // 15: rockim.shared.types.Paginated
}
var file_api_rockim_service_platform_v1_plat_user_proto_depIdxs = []int32{
	0,  // 0: rockim.service.platform.v1.PlatUserCreateRequest.options:type_name -> rockim.service.platform.v1.PlatUserOptions
	0,  // 1: rockim.service.platform.v1.PlatUserUpdateRequest.options:type_name -> rockim.service.platform.v1.PlatUserOptions
	13, // 2: rockim.service.platform.v1.PlatUserPagingRequest.paginate:type_name -> rockim.shared.types.Paginating
	14, // 3: rockim.service.platform.v1.PlatUserPagingResponse.list:type_name -> rockim.service.platform.v1.types.PlatUser
	15, // 4: rockim.service.platform.v1.PlatUserPagingResponse.paginate:type_name -> rockim.shared.types.Paginated
	14, // 5: rockim.service.platform.v1.PlatUserFindResponse.user:type_name -> rockim.service.platform.v1.types.PlatUser
	1,  // 6: rockim.service.platform.v1.PlatUserAPI.Create:input_type -> rockim.service.platform.v1.PlatUserCreateRequest
	3,  // 7: rockim.service.platform.v1.PlatUserAPI.Update:input_type -> rockim.service.platform.v1.PlatUserUpdateRequest
	5,  // 8: rockim.service.platform.v1.PlatUserAPI.Delete:input_type -> rockim.service.platform.v1.PlatUserDeleteRequest
	7,  // 9: rockim.service.platform.v1.PlatUserAPI.Paging:input_type -> rockim.service.platform.v1.PlatUserPagingRequest
	9,  // 10: rockim.service.platform.v1.PlatUserAPI.Find:input_type -> rockim.service.platform.v1.PlatUserFindRequest
	11, // 11: rockim.service.platform.v1.PlatUserAPI.ListRoleId:input_type -> rockim.service.platform.v1.PlatUserRoleIdListRequest
	2,  // 12: rockim.service.platform.v1.PlatUserAPI.Create:output_type -> rockim.service.platform.v1.PlatUserCreateResponse
	4,  // 13: rockim.service.platform.v1.PlatUserAPI.Update:output_type -> rockim.service.platform.v1.PlatUserUpdateResponse
	6,  // 14: rockim.service.platform.v1.PlatUserAPI.Delete:output_type -> rockim.service.platform.v1.PlatUserDeleteResponse
	8,  // 15: rockim.service.platform.v1.PlatUserAPI.Paging:output_type -> rockim.service.platform.v1.PlatUserPagingResponse
	10, // 16: rockim.service.platform.v1.PlatUserAPI.Find:output_type -> rockim.service.platform.v1.PlatUserFindResponse
	12, // 17: rockim.service.platform.v1.PlatUserAPI.ListRoleId:output_type -> rockim.service.platform.v1.PlatUserRoleIdListResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_rockim_service_platform_v1_plat_user_proto_init() }
func file_api_rockim_service_platform_v1_plat_user_proto_init() {
	if File_api_rockim_service_platform_v1_plat_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatUserOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatUserCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatUserCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatUserUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatUserUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatUserDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatUserDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatUserPagingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatUserPagingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatUserFindRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatUserFindResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatUserRoleIdListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rockim_service_platform_v1_plat_user_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatUserRoleIdListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_rockim_service_platform_v1_plat_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_rockim_service_platform_v1_plat_user_proto_goTypes,
		DependencyIndexes: file_api_rockim_service_platform_v1_plat_user_proto_depIdxs,
		MessageInfos:      file_api_rockim_service_platform_v1_plat_user_proto_msgTypes,
	}.Build()
	File_api_rockim_service_platform_v1_plat_user_proto = out.File
	file_api_rockim_service_platform_v1_plat_user_proto_rawDesc = nil
	file_api_rockim_service_platform_v1_plat_user_proto_goTypes = nil
	file_api_rockim_service_platform_v1_plat_user_proto_depIdxs = nil
}
