// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: rockim/service/message/v1/conversation.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ConversationListRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ConversationListRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConversationListRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ConversationListRequestMultiError, or nil if none found.
func (m *ConversationListRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ConversationListRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetBase() == nil {
		err := ConversationListRequestValidationError{
			field:  "Base",
			reason: "value is required",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if all {
		switch v := interface{}(m.GetBase()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ConversationListRequestValidationError{
					field:  "Base",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ConversationListRequestValidationError{
					field:  "Base",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBase()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ConversationListRequestValidationError{
				field:  "Base",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if utf8.RuneCountInString(m.GetUid()) < 1 {
		err := ConversationListRequestValidationError{
			field:  "Uid",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ConversationListRequestMultiError(errors)
	}

	return nil
}

// ConversationListRequestMultiError is an error wrapping multiple validation
// errors returned by ConversationListRequest.ValidateAll() if the designated
// constraints aren't met.
type ConversationListRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConversationListRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConversationListRequestMultiError) AllErrors() []error { return m }

// ConversationListRequestValidationError is the validation error returned by
// ConversationListRequest.Validate if the designated constraints aren't met.
type ConversationListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConversationListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConversationListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConversationListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConversationListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConversationListRequestValidationError) ErrorName() string {
	return "ConversationListRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ConversationListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConversationListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConversationListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConversationListRequestValidationError{}

// Validate checks the field values on ConversationListItem with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ConversationListItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConversationListItem with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ConversationListItemMultiError, or nil if none found.
func (m *ConversationListItem) ValidateAll() error {
	return m.validate(true)
}

func (m *ConversationListItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetConversation()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ConversationListItemValidationError{
					field:  "Conversation",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ConversationListItemValidationError{
					field:  "Conversation",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetConversation()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ConversationListItemValidationError{
				field:  "Conversation",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ConversationListItemMultiError(errors)
	}

	return nil
}

// ConversationListItemMultiError is an error wrapping multiple validation
// errors returned by ConversationListItem.ValidateAll() if the designated
// constraints aren't met.
type ConversationListItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConversationListItemMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConversationListItemMultiError) AllErrors() []error { return m }

// ConversationListItemValidationError is the validation error returned by
// ConversationListItem.Validate if the designated constraints aren't met.
type ConversationListItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConversationListItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConversationListItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConversationListItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConversationListItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConversationListItemValidationError) ErrorName() string {
	return "ConversationListItemValidationError"
}

// Error satisfies the builtin error interface
func (e ConversationListItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConversationListItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConversationListItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConversationListItemValidationError{}

// Validate checks the field values on ConversationListResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ConversationListResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ConversationListResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ConversationListResponseMultiError, or nil if none found.
func (m *ConversationListResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ConversationListResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ConversationListResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ConversationListResponseValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ConversationListResponseValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ConversationListResponseMultiError(errors)
	}

	return nil
}

// ConversationListResponseMultiError is an error wrapping multiple validation
// errors returned by ConversationListResponse.ValidateAll() if the designated
// constraints aren't met.
type ConversationListResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConversationListResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConversationListResponseMultiError) AllErrors() []error { return m }

// ConversationListResponseValidationError is the validation error returned by
// ConversationListResponse.Validate if the designated constraints aren't met.
type ConversationListResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConversationListResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConversationListResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConversationListResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConversationListResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConversationListResponseValidationError) ErrorName() string {
	return "ConversationListResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ConversationListResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConversationListResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConversationListResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConversationListResponseValidationError{}
