// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.0
// source: rockim/service/message/v1/conversation.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConversationAPIClient is the client API for ConversationAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConversationAPIClient interface {
	// List 获取会话列表
	List(ctx context.Context, in *ConversationListRequest, opts ...grpc.CallOption) (*ConversationListResponse, error)
}

type conversationAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewConversationAPIClient(cc grpc.ClientConnInterface) ConversationAPIClient {
	return &conversationAPIClient{cc}
}

func (c *conversationAPIClient) List(ctx context.Context, in *ConversationListRequest, opts ...grpc.CallOption) (*ConversationListResponse, error) {
	out := new(ConversationListResponse)
	err := c.cc.Invoke(ctx, "/rockim.service.message.v1.ConversationAPI/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConversationAPIServer is the server API for ConversationAPI service.
// All implementations must embed UnimplementedConversationAPIServer
// for forward compatibility
type ConversationAPIServer interface {
	// List 获取会话列表
	List(context.Context, *ConversationListRequest) (*ConversationListResponse, error)
	mustEmbedUnimplementedConversationAPIServer()
}

// UnimplementedConversationAPIServer must be embedded to have forward compatible implementations.
type UnimplementedConversationAPIServer struct {
}

func (UnimplementedConversationAPIServer) List(context.Context, *ConversationListRequest) (*ConversationListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedConversationAPIServer) mustEmbedUnimplementedConversationAPIServer() {}

// UnsafeConversationAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConversationAPIServer will
// result in compilation errors.
type UnsafeConversationAPIServer interface {
	mustEmbedUnimplementedConversationAPIServer()
}

func RegisterConversationAPIServer(s grpc.ServiceRegistrar, srv ConversationAPIServer) {
	s.RegisterService(&ConversationAPI_ServiceDesc, srv)
}

func _ConversationAPI_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConversationListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationAPIServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rockim.service.message.v1.ConversationAPI/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationAPIServer).List(ctx, req.(*ConversationListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConversationAPI_ServiceDesc is the grpc.ServiceDesc for ConversationAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConversationAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rockim.service.message.v1.ConversationAPI",
	HandlerType: (*ConversationAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ConversationAPI_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rockim/service/message/v1/conversation.proto",
}
