// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.0
// source: rockim/api/client/socket/v1/options.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operation Operation `protobuf:"varint,1,opt,name=operation,proto3,enum=rockim.api.client.socket.v1.Operation" json:"operation,omitempty"`
}

func (x *RequestOptions) Reset() {
	*x = RequestOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rockim_api_client_socket_v1_options_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOptions) ProtoMessage() {}

func (x *RequestOptions) ProtoReflect() protoreflect.Message {
	mi := &file_rockim_api_client_socket_v1_options_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOptions.ProtoReflect.Descriptor instead.
func (*RequestOptions) Descriptor() ([]byte, []int) {
	return file_rockim_api_client_socket_v1_options_proto_rawDescGZIP(), []int{0}
}

func (x *RequestOptions) GetOperation() Operation {
	if x != nil {
		return x.Operation
	}
	return Operation_INVALID_REQUEST
}

var file_rockim_api_client_socket_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*RequestOptions)(nil),
		Field:         3001,
		Name:          "rockim.api.client.socket.v1.request",
		Tag:           "bytes,3001,opt,name=request",
		Filename:      "rockim/api/client/socket/v1/options.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional rockim.api.client.socket.v1.RequestOptions request = 3001;
	E_Request = &file_rockim_api_client_socket_v1_options_proto_extTypes[0]
)

var File_rockim_api_client_socket_v1_options_proto protoreflect.FileDescriptor

var file_rockim_api_client_socket_v1_options_proto_rawDesc = []byte{
	0x0a, 0x29, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2f, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x72, 0x6f, 0x63,
	0x6b, 0x69, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x73,
	0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x28, 0x72, 0x6f, 0x63, 0x6b,
	0x69, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x73, 0x6f,
	0x63, 0x6b, 0x65, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x56, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x44, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x72, 0x6f, 0x63, 0x6b,
	0x69, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x73, 0x6f,
	0x63, 0x6b, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x3a, 0x66, 0x0a, 0x07,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xb9, 0x17, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b,
	0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x2e, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x42, 0x32, 0x5a, 0x30, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x2f, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x73, 0x6f, 0x63, 0x6b,
	0x65, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rockim_api_client_socket_v1_options_proto_rawDescOnce sync.Once
	file_rockim_api_client_socket_v1_options_proto_rawDescData = file_rockim_api_client_socket_v1_options_proto_rawDesc
)

func file_rockim_api_client_socket_v1_options_proto_rawDescGZIP() []byte {
	file_rockim_api_client_socket_v1_options_proto_rawDescOnce.Do(func() {
		file_rockim_api_client_socket_v1_options_proto_rawDescData = protoimpl.X.CompressGZIP(file_rockim_api_client_socket_v1_options_proto_rawDescData)
	})
	return file_rockim_api_client_socket_v1_options_proto_rawDescData
}

var file_rockim_api_client_socket_v1_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rockim_api_client_socket_v1_options_proto_goTypes = []interface{}{
	(*RequestOptions)(nil),             // 0: rockim.api.client.socket.v1.RequestOptions
	(Operation)(0),                     // 1: rockim.api.client.socket.v1.Operation
	(*descriptorpb.MethodOptions)(nil), // 2: google.protobuf.MethodOptions
}
var file_rockim_api_client_socket_v1_options_proto_depIdxs = []int32{
	1, // 0: rockim.api.client.socket.v1.RequestOptions.operation:type_name -> rockim.api.client.socket.v1.Operation
	2, // 1: rockim.api.client.socket.v1.request:extendee -> google.protobuf.MethodOptions
	0, // 2: rockim.api.client.socket.v1.request:type_name -> rockim.api.client.socket.v1.RequestOptions
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rockim_api_client_socket_v1_options_proto_init() }
func file_rockim_api_client_socket_v1_options_proto_init() {
	if File_rockim_api_client_socket_v1_options_proto != nil {
		return
	}
	file_rockim_api_client_socket_v1_socket_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rockim_api_client_socket_v1_options_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rockim_api_client_socket_v1_options_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_rockim_api_client_socket_v1_options_proto_goTypes,
		DependencyIndexes: file_rockim_api_client_socket_v1_options_proto_depIdxs,
		MessageInfos:      file_rockim_api_client_socket_v1_options_proto_msgTypes,
		ExtensionInfos:    file_rockim_api_client_socket_v1_options_proto_extTypes,
	}.Build()
	File_rockim_api_client_socket_v1_options_proto = out.File
	file_rockim_api_client_socket_v1_options_proto_rawDesc = nil
	file_rockim_api_client_socket_v1_options_proto_goTypes = nil
	file_rockim_api_client_socket_v1_options_proto_depIdxs = nil
}
func (x *RequestOptions) SetOperation(operation Operation) {
	if x == nil {
		return
	}
	x.Operation = operation
}
