// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.3
// - protoc             v3.20.0
// source: rockim/api/openapi/v1/chatroom.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationChatRoomAPICreate = "/rockim.api.openapi.v1.ChatRoomAPI/Create"

type ChatRoomAPIHTTPServer interface {
	// Create Create 创建聊天室
	Create(context.Context, *ChatRoomCreateRequest) (*ChatRoomCreateResponse, error)
}

func RegisterChatRoomAPIHTTPServer(s *http.Server, srv ChatRoomAPIHTTPServer) {
	r := s.Route("/")
	r.POST("/openapi/v1/chatroom/create", _ChatRoomAPI_Create0_HTTP_Handler(srv))
}

func _ChatRoomAPI_Create0_HTTP_Handler(srv ChatRoomAPIHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ChatRoomCreateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationChatRoomAPICreate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Create(ctx, req.(*ChatRoomCreateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChatRoomCreateResponse)
		return ctx.Result(200, reply)
	}
}

type ChatRoomAPIHTTPClient interface {
	Create(ctx context.Context, req *ChatRoomCreateRequest, opts ...http.CallOption) (rsp *ChatRoomCreateResponse, err error)
}

type ChatRoomAPIHTTPClientImpl struct {
	cc *http.Client
}

func NewChatRoomAPIHTTPClient(client *http.Client) ChatRoomAPIHTTPClient {
	return &ChatRoomAPIHTTPClientImpl{client}
}

func (c *ChatRoomAPIHTTPClientImpl) Create(ctx context.Context, in *ChatRoomCreateRequest, opts ...http.CallOption) (*ChatRoomCreateResponse, error) {
	var out ChatRoomCreateResponse
	pattern := "/openapi/v1/chatroom/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationChatRoomAPICreate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
