// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.20.0
// source: rockim/service/comet/v1/types/comet.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	enums "rockimserver/apis/rockim/shared/enums"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Room 房间
type Room struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomType enums.Comet_RoomType `protobuf:"varint,1,opt,name=room_type,json=roomType,proto3,enum=rockim.shared.enums.Comet_RoomType" json:"room_type,omitempty"`
	BizId    string               `protobuf:"bytes,2,opt,name=biz_id,json=bizId,proto3" json:"biz_id,omitempty"`
}

func (x *Room) Reset() {
	*x = Room{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rockim_service_comet_v1_types_comet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Room) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Room) ProtoMessage() {}

func (x *Room) ProtoReflect() protoreflect.Message {
	mi := &file_rockim_service_comet_v1_types_comet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Room.ProtoReflect.Descriptor instead.
func (*Room) Descriptor() ([]byte, []int) {
	return file_rockim_service_comet_v1_types_comet_proto_rawDescGZIP(), []int{0}
}

func (x *Room) GetRoomType() enums.Comet_RoomType {
	if x != nil {
		return x.RoomType
	}
	return enums.Comet_GROUP
}

func (x *Room) GetBizId() string {
	if x != nil {
		return x.BizId
	}
	return ""
}

// Message 消息
type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 消息类型
	DataType enums.Comet_DataType `protobuf:"varint,1,opt,name=data_type,json=dataType,proto3,enum=rockim.shared.enums.Comet_DataType" json:"data_type,omitempty"`
	// 控制消息
	Control *ControlMessage `protobuf:"bytes,2,opt,name=control,proto3" json:"control,omitempty"`
	// 推送消息
	Push *PushMessage `protobuf:"bytes,3,opt,name=push,proto3" json:"push,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rockim_service_comet_v1_types_comet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_rockim_service_comet_v1_types_comet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_rockim_service_comet_v1_types_comet_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetDataType() enums.Comet_DataType {
	if x != nil {
		return x.DataType
	}
	return enums.Comet_PUSH
}

func (x *Message) GetControl() *ControlMessage {
	if x != nil {
		return x.Control
	}
	return nil
}

func (x *Message) GetPush() *PushMessage {
	if x != nil {
		return x.Push
	}
	return nil
}

type PushMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operation enums.Comet_PushOperation `protobuf:"varint,1,opt,name=operation,proto3,enum=rockim.shared.enums.Comet_PushOperation" json:"operation,omitempty"`
	// 推送内容
	Body []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *PushMessage) Reset() {
	*x = PushMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rockim_service_comet_v1_types_comet_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessage) ProtoMessage() {}

func (x *PushMessage) ProtoReflect() protoreflect.Message {
	mi := &file_rockim_service_comet_v1_types_comet_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessage.ProtoReflect.Descriptor instead.
func (*PushMessage) Descriptor() ([]byte, []int) {
	return file_rockim_service_comet_v1_types_comet_proto_rawDescGZIP(), []int{2}
}

func (x *PushMessage) GetOperation() enums.Comet_PushOperation {
	if x != nil {
		return x.Operation
	}
	return enums.Comet_INVALID_PUSH
}

func (x *PushMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type ControlMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ControlType 控制类型
	// 控制类型
	ControlType enums.Comet_ControlType `protobuf:"varint,2,opt,name=control_type,json=controlType,proto3,enum=rockim.shared.enums.Comet_ControlType" json:"control_type,omitempty"`
	// 控制内容
	Body []byte `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rockim_service_comet_v1_types_comet_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_rockim_service_comet_v1_types_comet_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_rockim_service_comet_v1_types_comet_proto_rawDescGZIP(), []int{3}
}

func (x *ControlMessage) GetControlType() enums.Comet_ControlType {
	if x != nil {
		return x.ControlType
	}
	return enums.Comet_UNKNOWN
}

func (x *ControlMessage) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// RoomJoinControl 加入房间控制
type RoomJoinControl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rooms []*Room `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
}

func (x *RoomJoinControl) Reset() {
	*x = RoomJoinControl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rockim_service_comet_v1_types_comet_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomJoinControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomJoinControl) ProtoMessage() {}

func (x *RoomJoinControl) ProtoReflect() protoreflect.Message {
	mi := &file_rockim_service_comet_v1_types_comet_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomJoinControl.ProtoReflect.Descriptor instead.
func (*RoomJoinControl) Descriptor() ([]byte, []int) {
	return file_rockim_service_comet_v1_types_comet_proto_rawDescGZIP(), []int{4}
}

func (x *RoomJoinControl) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

// RoomQuitControl 退出房间控制
type RoomQuitControl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rooms []*Room `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
}

func (x *RoomQuitControl) Reset() {
	*x = RoomQuitControl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rockim_service_comet_v1_types_comet_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomQuitControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomQuitControl) ProtoMessage() {}

func (x *RoomQuitControl) ProtoReflect() protoreflect.Message {
	mi := &file_rockim_service_comet_v1_types_comet_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomQuitControl.ProtoReflect.Descriptor instead.
func (*RoomQuitControl) Descriptor() ([]byte, []int) {
	return file_rockim_service_comet_v1_types_comet_proto_rawDescGZIP(), []int{5}
}

func (x *RoomQuitControl) GetRooms() []*Room {
	if x != nil {
		return x.Rooms
	}
	return nil
}

// KickOffControl 踢下线控制
type KickOffControl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KickOffControl) Reset() {
	*x = KickOffControl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rockim_service_comet_v1_types_comet_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KickOffControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickOffControl) ProtoMessage() {}

func (x *KickOffControl) ProtoReflect() protoreflect.Message {
	mi := &file_rockim_service_comet_v1_types_comet_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickOffControl.ProtoReflect.Descriptor instead.
func (*KickOffControl) Descriptor() ([]byte, []int) {
	return file_rockim_service_comet_v1_types_comet_proto_rawDescGZIP(), []int{6}
}

var File_rockim_service_comet_v1_types_comet_proto protoreflect.FileDescriptor

var file_rockim_service_comet_v1_types_comet_proto_rawDesc = []byte{
	0x0a, 0x29, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f,
	0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1d, 0x72, 0x6f, 0x63,
	0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x65,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x1a, 0x1f, 0x72, 0x6f, 0x63, 0x6b,
	0x69, 0x6d, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2f,
	0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5f, 0x0a, 0x04, 0x52,
	0x6f, 0x6f, 0x6d, 0x12, 0x40, 0x0a, 0x09, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x43, 0x6f, 0x6d,
	0x65, 0x74, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x72, 0x6f, 0x6f,
	0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x69, 0x7a, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x69, 0x7a, 0x49, 0x64, 0x22, 0xd4, 0x01, 0x0a,
	0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x40, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x23, 0x2e, 0x72, 0x6f,
	0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x65, 0x6e, 0x75, 0x6d,
	0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x47, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x72, 0x6f,
	0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x6f, 0x6d,
	0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x12, 0x3e, 0x0a, 0x04, 0x70, 0x75, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x2a, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x70,
	0x75, 0x73, 0x68, 0x22, 0x69, 0x0a, 0x0b, 0x50, 0x75, 0x73, 0x68, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x46, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73,
	0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x43, 0x6f, 0x6d, 0x65,
	0x74, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x6f,
	0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x49, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e,
	0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x65, 0x6e, 0x75, 0x6d, 0x73, 0x2e, 0x43, 0x6f, 0x6d,
	0x65, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22,
	0x4c, 0x0a, 0x0f, 0x52, 0x6f, 0x6f, 0x6d, 0x4a, 0x6f, 0x69, 0x6e, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x12, 0x39, 0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x22, 0x4c, 0x0a,
	0x0f, 0x52, 0x6f, 0x6f, 0x6d, 0x51, 0x75, 0x69, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x12, 0x39, 0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x05, 0x72, 0x6f, 0x6f, 0x6d, 0x73, 0x22, 0x10, 0x0a, 0x0e, 0x4b,
	0x69, 0x63, 0x6b, 0x4f, 0x66, 0x66, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x42, 0x37, 0x5a,
	0x35, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70,
	0x69, 0x73, 0x2f, 0x72, 0x6f, 0x63, 0x6b, 0x69, 0x6d, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x65, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x3b, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rockim_service_comet_v1_types_comet_proto_rawDescOnce sync.Once
	file_rockim_service_comet_v1_types_comet_proto_rawDescData = file_rockim_service_comet_v1_types_comet_proto_rawDesc
)

func file_rockim_service_comet_v1_types_comet_proto_rawDescGZIP() []byte {
	file_rockim_service_comet_v1_types_comet_proto_rawDescOnce.Do(func() {
		file_rockim_service_comet_v1_types_comet_proto_rawDescData = protoimpl.X.CompressGZIP(file_rockim_service_comet_v1_types_comet_proto_rawDescData)
	})
	return file_rockim_service_comet_v1_types_comet_proto_rawDescData
}

var file_rockim_service_comet_v1_types_comet_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rockim_service_comet_v1_types_comet_proto_goTypes = []interface{}{
	(*Room)(nil),                   // 0: rockim.service.comet.v1.types.Room
	(*Message)(nil),                // 1: rockim.service.comet.v1.types.Message
	(*PushMessage)(nil),            // 2: rockim.service.comet.v1.types.PushMessage
	(*ControlMessage)(nil),         // 3: rockim.service.comet.v1.types.ControlMessage
	(*RoomJoinControl)(nil),        // 4: rockim.service.comet.v1.types.RoomJoinControl
	(*RoomQuitControl)(nil),        // 5: rockim.service.comet.v1.types.RoomQuitControl
	(*KickOffControl)(nil),         // 6: rockim.service.comet.v1.types.KickOffControl
	(enums.Comet_RoomType)(0),      // 7: rockim.shared.enums.Comet.RoomType
	(enums.Comet_DataType)(0),      // 8: rockim.shared.enums.Comet.DataType
	(enums.Comet_PushOperation)(0), // 9: rockim.shared.enums.Comet.PushOperation
	(enums.Comet_ControlType)(0),   // 10: rockim.shared.enums.Comet.ControlType
}
var file_rockim_service_comet_v1_types_comet_proto_depIdxs = []int32{
	7,  // 0: rockim.service.comet.v1.types.Room.room_type:type_name -> rockim.shared.enums.Comet.RoomType
	8,  // 1: rockim.service.comet.v1.types.Message.data_type:type_name -> rockim.shared.enums.Comet.DataType
	3,  // 2: rockim.service.comet.v1.types.Message.control:type_name -> rockim.service.comet.v1.types.ControlMessage
	2,  // 3: rockim.service.comet.v1.types.Message.push:type_name -> rockim.service.comet.v1.types.PushMessage
	9,  // 4: rockim.service.comet.v1.types.PushMessage.operation:type_name -> rockim.shared.enums.Comet.PushOperation
	10, // 5: rockim.service.comet.v1.types.ControlMessage.control_type:type_name -> rockim.shared.enums.Comet.ControlType
	0,  // 6: rockim.service.comet.v1.types.RoomJoinControl.rooms:type_name -> rockim.service.comet.v1.types.Room
	0,  // 7: rockim.service.comet.v1.types.RoomQuitControl.rooms:type_name -> rockim.service.comet.v1.types.Room
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_rockim_service_comet_v1_types_comet_proto_init() }
func file_rockim_service_comet_v1_types_comet_proto_init() {
	if File_rockim_service_comet_v1_types_comet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rockim_service_comet_v1_types_comet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Room); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rockim_service_comet_v1_types_comet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rockim_service_comet_v1_types_comet_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rockim_service_comet_v1_types_comet_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControlMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rockim_service_comet_v1_types_comet_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomJoinControl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rockim_service_comet_v1_types_comet_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomQuitControl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rockim_service_comet_v1_types_comet_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KickOffControl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rockim_service_comet_v1_types_comet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rockim_service_comet_v1_types_comet_proto_goTypes,
		DependencyIndexes: file_rockim_service_comet_v1_types_comet_proto_depIdxs,
		MessageInfos:      file_rockim_service_comet_v1_types_comet_proto_msgTypes,
	}.Build()
	File_rockim_service_comet_v1_types_comet_proto = out.File
	file_rockim_service_comet_v1_types_comet_proto_rawDesc = nil
	file_rockim_service_comet_v1_types_comet_proto_goTypes = nil
	file_rockim_service_comet_v1_types_comet_proto_depIdxs = nil
}
